name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - hexo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog source
        uses: actions/checkout@v4
        with:
          path: blog

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: blog/package-lock.json

      - name: Install node-pre-gyp globally
        run: npm install -g node-pre-gyp
        working-directory: ./blog

      - name: Set correct permissions for node_modules
        run: chmod -R 755 ./node_modules
        working-directory: ./blog

      - name: Install dependencies (Linux rebuild)
        run: |
          npm install --target_platform=linux --target_arch=x64 --force
          npm rebuild nodejieba --update-binary
        working-directory: ./blog

      - name: Install Hexo CLI
        run: npm install -g hexo-cli
        working-directory: ./blog

      - name: Clean and Generate static pages
        run: |
          #hexoclean
          hexo generate
        working-directory: ./blog

      - name: Fetch and merge remote changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add target https://github.com/YQYStudio/YQYStudio.github.io.git
          git fetch target main
          git merge target/main
        working-directory: ./blog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}  # 改用 SSH 密钥
          publish_dir: ./blog/public
          external_repository: YQYStudio/YQYStudio.github.io
          publish_branch: main
          commit_message: 'Automated deploy: ${{ github.sha }}'
          force_orphan: true
